### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Algabri** [deshanadesai/online-boosting#1]
I opened the new terminal: ### python compare_weaklearners.py data

I found this error:

```
Dataset not found.
training Naive Bayes
Traceback (most recent call last):
  File "compare_weaklearners.py", line 75, in <module>
    OnlineLearners()
  File "compare_weaklearners.py", line 20, in __init__
    self.run()
  File "compare_weaklearners.py", line 64, in run
    yy_.append(incorrect/X_test.shape[0])
AttributeError: 'list' object has no attribute 'shape'
```

please, help me out.

Thanks in advance.

**Comment by deshanadesai** [comment]
Hi Algabri, I took a quick look and X_test seems to be an empty list for you. This means the data is not load properly. You may have to add an additional clause for your dataset in the load_data() function here: https://github.com/deshanadesai/GreedyBoost/blob/master/data_loader.py

**Comment by Algabri** [comment]
I see,  deshanadesai.
It is working now.
Thanks.
