### ISSUE TITLE
No method for fit or partial_fit

### ISSUE THREAD

**Issue by Algabri** [deshanadesai/online-boosting#2]
No method for fit or partial_fit with osboost, ocpboost, expboost, ozaboost, smoothboost, and ogboost.

How to train the data using one of them, then predict new data?

Thanks.

**Comment by deshanadesai** [comment]
Hi @Algabri , since this is an online learning setting - instead of the concept of fitting with a static training set, the data may appear one at a time for training and is in that sense - a dynamic training set. Instead of the fit method, there is an update method for each of these algorithms.

Example: https://github.com/deshanadesai/GreedyBoost/blob/04a6bf038e7724ae6438f00fcf38f3ef8c4d78c9/ensembles/ogboost.py#L29

For prediction, please call the classify method.

As for partial fits, you would find that in the base learners: https://github.com/deshanadesai/GreedyBoost/blob/04a6bf038e7724ae6438f00fcf38f3ef8c4d78c9/learners/nb.py#L24

**Comment by Algabri** [comment]
I tried to implement it as you suggested.

This is a small code:


`from sklearn.datasets import load_iris
from ensembles import osboost, ocpboost, expboost, ozaboost, smoothboost, ogboost
from learners import nb_gaussian,sk_nb, nb, perceptron, sk_perceptron, random_stump, sk_decisiontree, sk_gaussian #, decision_trees

X, y = load_iris(return_X_y=True)
data = load_iris()
target = data.target_names
print (target)
clf = osboost.OSBoost(learners=nb, classes=target, total_points= 10, gamma= 0.1)`

sadly, this error happened, if you know my mistake where was, help me, please.

`Traceback (most recent call last):
['setosa' 'versicolor' 'virginica']
  File "/home/redhwan/1/paper4/GreedyBoost-master/learn.py", line 10, in <module>
    clf = osboost.OSBoost(learners=nb, classes=target, total_points= 10, gamma= 0.1)
  File "/home/redhwan/1/paper4/GreedyBoost-master/ensembles/osboost.py", line 8, in __init__
    self.learners = [learners(classes) for i in range(self.M)]
TypeError: 'module' object is not callable`

**Comment by Algabri** [comment]
Also, when did like that, the same:

```
from random import seed

import matplotlib
from sklearn.datasets import load_iris
matplotlib.use('Agg')

from sklearn.model_selection import train_test_split

from ensembles import osboost, ocpboost, expboost, ozaboost, smoothboost, ogboost
import warnings


warnings.filterwarnings(action='ignore')

from learners import nb_gaussian, sk_nb, nb, perceptron, random_stump, sk_gaussian, sk_decisiontree, \
    sk_perceptron  # , decision_trees



class OnlineLearners():
    def __init__(self):
        self.learner = None
        self.run()

    def run(self):
        seed(0)

        import numpy as np

        # data = np.genfromtxt('./data_jf/join_f4.csv', delimiter=",")
        data = load_iris()

        X, y = data.data, data.target
        # print X, y
        y = np.where(y > 0, 1, -1)
        Y = y.astype(int)

        rng = np.random.RandomState(42)


        X_train, X_test, y_train, y_test = train_test_split(X, Y,  random_state=rng)

        data = zip(X_train, y_train)
        classes = np.unique(np.array([y for (x, y) in data]))
        print classes
        clf = osboost.OSBoost(learners=nb, classes=classes)

OnlineLearners()
```
